{{- if .Values.ingress -}}
{{- if .Values.ingress.rules -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "template.fullname" . }}
  labels:
    app: {{ template "template.name" . }}
    chart: {{ template "template.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: $1
spec:
  tls:
  {{- range $rule := .Values.ingress.rules }}
    - hosts:
      - {{ default $rule.subDomain "h" }}.{{ required "ingress.domain is required" $.Values.ingress.domain }}
      secretName: {{ default "default-ingress-cert" $rule.tlsSecret }}
  {{- end }}
  rules:
  {{- range $rule := .Values.ingress.rules }}
    - host: {{ default $rule.subDomain "h" }}.{{ $.Values.ingress.domain }}
      http:
        paths:
        {{- range $backend := $rule.backends }}
          - backend:
              serviceName: {{ template "template.fullname" $ }}
              servicePort: {{ $backend.port }}
            {{- if or $rule.pathPrefix $backend.path }}
              {{- $prefix := default "" $rule.pathPrefix }}
              {{- $path := default "" $backend.path }}
            path: {{ clean (printf "/%s/%s" $prefix $path) }}(.*)
            {{- end }}
        {{- end}}
  {{- end }}
{{ else }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "template.fullname" . }}
  labels:
    app: {{ template "template.name" . }}
    chart: {{ template "template.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: $1
spec:
  tls:
  - hosts:
    - h.{{ required "ingress.domain is required" $.Values.ingress.domain }}
    secretName: "default-ingress-cert"
  rules:
    - host: h.{{ $.Values.ingress.domain }}
      http:
        paths:
          - backend:
              serviceName: {{ template "template.fullname" $ }}
              {{- if .Values.environment}}
              servicePort: {{ default 8080 (get .Values.environment "PORT") }}
              {{- else }}
              servicePort: 8080
              {{- end }}
            path: /s/{{ .Release.Name }}(.*)
{{- end }}
{{- end -}}
