{{- $replicas := .Values.replicas | default 1.0 -}}
{{- if and .Values.minAvailable (gt $replicas 1.0) }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    app: {{ template "template.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "template.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ template "template.name" . }}
      release: {{ .Release.Name }}
  minAvailable: {{ .Values.minAvailable }}
{{- end }}
