{{- if .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "template.fullname" . }}
  labels:
    app: {{ template "template.name" . }}
    chart: {{ template "template.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: kubernetes.io/Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | toString | b64enc }}
  {{- end }}
{{- end }}

{{- if .Values.files }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "template.fullname" . }}-files
  labels:
    app: {{ template "template.name" . }}
    chart: {{ template "template.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: kubernetes.io/Opaque
data:
  {{- range $key, $value := .Values.files }}
  file{{ $key | replace "." "-" | replace "/" "_" }}: {{ $value | toString | b64enc }}
  {{- end }}
{{- end }}
