#! /bin/bash

# Setup "safe" bash script, releative to scripts location
set -euxo pipefail
cd "$(dirname "$0")"

# Function to test multiple different dockerfile configs with same result.
function runTest {
  # Inject the proper image into the Dockerfile for building
  IMAGE="${SKYNET_APPLICATION_PLATFORM:-drydock-prod.workiva.net/workiva/platform:v0}"
  echo $IMAGE
  sed "s~IMAGE~${IMAGE}~g" $1.txt > Dockerfile
  cat Dockerfile
  cp Dockerfile $1.Dockerfile

  # Simulate Workiva-Build (contains checks against expected values)
  docker build --no-cache . | tee $1.log

  # Verify we properly detect first exposed port as the probe port
  grep -q "Using 2222 for readiness probe" $1.log
}

runTest original
runTest onbuild
